fedora:
    image: registry.gitlab.gnome.org/gnome/gvfs:latest
    script:
        - meson -Dinstalled_tests=true -Ddevel_utils=true -Dman=true --prefix /usr --werror build
        - ninja -C build install
        - GIO_USE_VOLUME_MONITOR=unix gnome-desktop-testing-runner gvfs

.gnome-build-meta-template: &gnome-build-meta
    variables:
        BST_SHA: '1.4.0-0-gf8ca130adb632614ebff8453fd91d4c96e87221d'
        BST_EXTERNAL_SHA: '0.18.0-0-g755206670c87a2999132025d24b0d0aacc611ef2'
        DOCKER_IMAGE_ID: '1a534a96f9144ca8ee87cee1fef97faa7c396533'
        DOCKER_REGISTRY: "registry.gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images"
        DOCKER_AMD64: "${DOCKER_REGISTRY}/bst14/amd64:${DOCKER_IMAGE_ID}"
    image: "${DOCKER_AMD64}"
    before_script:
        - pip3 uninstall -y buildstream
        - git clone https://gitlab.com/BuildStream/buildstream.git
        - git -C buildstream/ checkout $BST_SHA
        - pip3 install buildstream/
        - git clone https://gitlab.com/BuildStream/bst-external.git
        - git -C bst-external/ checkout $BST_EXTERNAL_SHA
        - pip3 install bst-external/
        - git clone --depth 1 https://gitlab.gnome.org/GNOME/gnome-build-meta.git
    script:
        - cd gnome-build-meta
        - bst build --track-all sdk/gvfs.bst
        - bst workspace open --no-checkout sdk/gvfs.bst ..
        - bst --no-interactive build sdk/gvfs.bst

gnome-build-meta-tags:
    <<: *gnome-build-meta
    only: [tags]

gnome-build-meta-manual:
    <<: *gnome-build-meta
    when: manual
    except: [tags]

update-image:
    variables:
         DOCKER_TLS_CERTDIR: ""
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker build --tag $CI_REGISTRY_IMAGE .gitlab-ci/
        - docker tag $CI_REGISTRY_IMAGE "$CI_REGISTRY_IMAGE:v$CI_JOB_ID"
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker push $CI_REGISTRY_IMAGE
    when: manual
    only:
        variables:
            - $CI_PROJECT_NAMESPACE == "GNOME"
