image: fedora:rawhide

before_script:
    - dnf install -y avahi-devel
                     avahi-glib-devel
                     dbus-glib-devel
                     docbook-style-xsl
                     fuse-devel
                     gcc
                     gcr-devel
                     gettext-devel
                     glib2-devel
                     gnome-desktop-testing
                     gnome-online-accounts-devel
                     libarchive-devel
                     libbluray-devel
                     libcap-devel
                     libcdio-paranoia-devel
                     libexif-devel
                     libgcrypt-devel
                     libgdata-devel
                     libgphoto2-devel
                     libgudev-devel
                     libimobiledevice-devel
                     libmtp-devel
                     libnfs-devel
                     libplist-devel
                     libsecret-devel
                     libsmbclient-devel
                     libsoup-devel
                     libtalloc-devel
                     libudisks2-devel
                     libusb-devel
                     libxslt-devel
                     meson
                     mod_ssl
                     openssh-clients
                     pkgconf-pkg-config
                     polkit-devel
                     python-twisted
                     python3
                     samba
                     systemd-devel

build:
    stage: build
    artifacts:
        untracked: true
        expire_in: 1h
    script:
        - meson -Dinstalled_tests=true _build .
        - ninja -C _build

test:
    stage: test
    script:
        - ninja -C _build install
        - gnome-desktop-testing-runner -d /usr/local/share/ gvfs
    allow_failure: true
