fedora:
    image: registry.gitlab.gnome.org/gnome/gvfs:latest
    tags:
        - x86_64
    script:
        - meson -Dinstalled_tests=true -Ddevel_utils=true -Dman=true --prefix /usr --werror build
        - sudo ninja -C build install
        - GIO_USE_VOLUME_MONITOR=unix gnome-desktop-testing-runner gvfs
    allow_failure: true

.gnome-build-meta-template: &gnome-build-meta
    variables:
        DOCKER_IMAGE_ID: 'e593f441b6ac7536b0e35a4354dc20c6c123f6b5'
        DOCKER_REGISTRY: "registry.gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images"
        DOCKER_AMD64: "${DOCKER_REGISTRY}/bst14/amd64:${DOCKER_IMAGE_ID}"
    image: "${DOCKER_AMD64}"
    before_script:
        - git clone --depth 1 https://gitlab.gnome.org/GNOME/gnome-build-meta.git
    script:
        - cd gnome-build-meta
        - bst build --track-all sdk/gvfs.bst
        - bst workspace open --no-checkout sdk/gvfs.bst ..
        - bst --no-interactive build sdk/gvfs.bst

gnome-build-meta-tags:
    <<: *gnome-build-meta
    only: [tags]

gnome-build-meta-manual:
    <<: *gnome-build-meta
    when: manual
    except: [tags]

update-image:
    variables:
         DOCKER_TLS_CERTDIR: ""
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker build --tag $CI_REGISTRY_IMAGE .gitlab-ci/
        - docker tag $CI_REGISTRY_IMAGE "$CI_REGISTRY_IMAGE:v$CI_JOB_ID"
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker push $CI_REGISTRY_IMAGE
    when: manual
    only:
        variables:
            - $CI_PROJECT_NAMESPACE == "GNOME"
