variables:
    NAME: "fedora"

fedora:
    stage: build
    image: "$CI_REGISTRY_IMAGE/$NAME"
    script:
        - meson build --werror
        - ninja -C build

gnome-build-meta:
    stage: build
    image: "$CI_REGISTRY_IMAGE/$NAME"
    script:
        - bst --directory /gnome-build-meta workspace open --no-checkout sdk/gvfs.bst .
        - bst --directory /gnome-build-meta build sdk/gvfs.bst

update-image:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker build --tag "$CI_REGISTRY_IMAGE/$NAME" .gitlab-ci/
        # The following can't be run from Dockerfile as it needs --privileged.
        - docker run --privileged --name $NAME "$CI_REGISTRY_IMAGE/$NAME" bash -c "cd gnome-build-meta && bst build --track-all sdk/gvfs.bst"
        - docker commit $NAME "$CI_REGISTRY_IMAGE:$NAME"
        - docker tag "$CI_REGISTRY_IMAGE/$NAME" "$CI_REGISTRY_IMAGE/$NAME:v$CI_JOB_ID"
        - docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
        - docker push "$CI_REGISTRY_IMAGE/$NAME"
    when: manual
