fedora:
    image: $CI_REGISTRY_IMAGE
    script:
        - meson -Dinstalled_tests=true --prefix /usr --werror build
        - ninja -C build install
        - GIO_USE_VOLUME_MONITOR=unix gnome-desktop-testing-runner gvfs

gnome-build-meta:
    image: buildstream/buildstream-fedora:master-123-abef70fe
    before_script:
        - pip3 uninstall -y buildstream
        - git clone https://gitlab.com/BuildStream/buildstream.git
        - git -C buildstream/ checkout 10abe77fe8d77385d86f225b503d9185f4ef7f3a
        - pip3 install buildstream/
        - git clone https://gitlab.com/BuildStream/bst-external.git
        - git -C bst-external/ checkout 0.8.0-0-g762ea216b751bf89ac15350e1cb98542963bbf33
        - pip3 install bst-external/
        - git clone --depth 1 https://gitlab.gnome.org/GNOME/gnome-build-meta.git
    script:
        - cd gnome-build-meta
        - bst build --track-all sdk/gvfs.bst
        - bst workspace open --no-checkout sdk/gvfs.bst ..
        - bst --no-interactive build sdk/gvfs.bst
    when: manual

update-image:
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker build --tag $CI_REGISTRY_IMAGE .gitlab-ci/
        - docker tag $CI_REGISTRY_IMAGE "$CI_REGISTRY_IMAGE:v$CI_JOB_ID"
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker push $CI_REGISTRY_IMAGE
    when: manual
