image: fedora:rawhide

before_script:
    - dnf install -y avahi-devel
                     avahi-glib-devel
                     dbus-glib-devel
                     docbook-style-xsl
                     fuse-devel
                     gcr-devel
                     gettext-devel
                     glib2-devel
                     gnome-online-accounts-devel
                     libarchive-devel
                     libbluray-devel
                     libcap-devel
                     libcdio-paranoia-devel
                     libexif-devel
                     libgcrypt-devel
                     libgdata-devel
                     libgphoto2-devel
                     libgudev-devel
                     libimobiledevice-devel
                     libmtp-devel
                     libnfs-devel
                     libplist-devel
                     libsecret-devel
                     libsmbclient-devel
                     libsoup-devel
                     libtalloc-devel
                     libudisks2-devel
                     libusb-devel
                     libxslt-devel
                     meson
                     openssh-clients
                     pkgconf-pkg-config
                     polkit-devel
                     systemd-devel

build:
    stage: build
    script:
        - meson _build .
        - ninja -C _build
