fedora:
    image: registry.gitlab.gnome.org/gnome/gvfs:latest
    tags:
        - x86_64
    script:
        - meson -Dinstalled_tests=true -Ddevel_utils=true -Dman=true --prefix /usr --werror build
        - sudo ninja -C build install
        - GIO_USE_VOLUME_MONITOR=unix gnome-desktop-testing-runner gvfs
    allow_failure: true

update-image:
    variables:
         DOCKER_TLS_CERTDIR: ""
    image: docker:latest
    tags:
        - privileged
    services:
        - docker:dind
    script:
        - docker build --tag $CI_REGISTRY_IMAGE .gitlab-ci/
        - docker tag $CI_REGISTRY_IMAGE "$CI_REGISTRY_IMAGE:v$CI_JOB_ID"
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker push $CI_REGISTRY_IMAGE
    when: manual
    only:
        variables:
            - $CI_PROJECT_NAMESPACE == "GNOME"
