image: fedora:rawhide
stages:
    - build
    - test

build:
    stage: build
    artifacts:
        untracked: true
        expire_in: 1 day
    before_script:
        - dnf install -y avahi-devel
                         avahi-glib-devel
                         dbus-glib-devel
                         docbook-style-xsl
                         fuse-devel
                         gcc
                         gcr-devel
                         gettext-devel
                         glib2-devel
                         gnome-online-accounts-devel
                         libarchive-devel
                         libbluray-devel
                         libcap-devel
                         libcdio-paranoia-devel
                         libexif-devel
                         libgcrypt-devel
                         libgdata-devel
                         libgphoto2-devel
                         libgudev-devel
                         libimobiledevice-devel
                         libmtp-devel
                         libnfs-devel
                         libplist-devel
                         libsecret-devel
                         libsmbclient-devel
                         libsoup-devel
                         libtalloc-devel
                         libudisks2-devel
                         libusb-devel
                         libxslt-devel
                         meson
                         openssh-clients
                         pkgconf-pkg-config
                         polkit-devel
                         systemd-devel
    script:
        - meson . _build -Dinstalled_tests=true
        - ninja -C _build
        - ninja -C _build install

test:
    stage: test
    before_script:
        - dnf install -y gnome-desktop-testing
                         mod_ssl
                         python3
                         python-twisted
                         samba
    script:
        - gnome-desktop-testing-runner -d gvfs
    allow_failure: true
