fedora:
    image: registry.gitlab.gnome.org/gnome/gvfs:latest
    script:
        - meson -Dinstalled_tests=true --prefix /usr --werror build
        - ninja -C build install
        - GIO_USE_VOLUME_MONITOR=unix gnome-desktop-testing-runner gvfs

.gnome-build-meta-template: &gnome-build-meta
    variables:
        BST_SHA: '1.2.4-3-g79bbefe26a3fcd13d3de558aed6b5b4d5bc1235a'
        BST_EXTERNAL_SHA: '0.9.0-0-g63a19e8068bd777bd9cd59b1a9442f9749ea5a85'
        DOCKER_REGISTRY: "registry.gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images"
        DOCKER_AMD64: "${DOCKER_REGISTRY}/amd64:e132e7bf9180b30c6ad0f4b057442cc2f2a0aa86"
    image: "${DOCKER_AMD64}"
    before_script:
        - pip3 uninstall -y buildstream
        - git clone https://gitlab.com/BuildStream/buildstream.git
        - git -C buildstream/ checkout $BST_SHA
        - pip3 install buildstream/
        - git clone https://gitlab.com/BuildStream/bst-external.git
        - git -C bst-external/ checkout $BST_EXTERNAL_SHA
        - pip3 install bst-external/
        - git clone --depth 1 https://gitlab.gnome.org/GNOME/gnome-build-meta.git
    script:
        - cd gnome-build-meta
        - bst build --track-all sdk/gvfs.bst
        - bst workspace open --no-checkout sdk/gvfs.bst ..
        - bst --no-interactive build sdk/gvfs.bst

gnome-build-meta-tags:
    <<: *gnome-build-meta
    only: [tags]

gnome-build-meta-manual:
    <<: *gnome-build-meta
    when: manual
    except: [tags]

update-image:
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker build --tag $CI_REGISTRY_IMAGE .gitlab-ci/
        - docker tag $CI_REGISTRY_IMAGE "$CI_REGISTRY_IMAGE:v$CI_JOB_ID"
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker push $CI_REGISTRY_IMAGE
    when: manual
