variables:
    NAME: "fedora"

fedora:
    stage: build
    image: "$CI_REGISTRY_IMAGE/$NAME"
    script:
        - meson build --werror
        - ninja -C build

update-image:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    script:
        - docker build --tag "$CI_REGISTRY_IMAGE/$NAME" .gitlab-ci/
        - docker tag "$CI_REGISTRY_IMAGE/$NAME" "$CI_REGISTRY_IMAGE/$NAME:v$CI_JOB_ID"
        - docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
        - docker push "$CI_REGISTRY_IMAGE/$NAME"
    when: manual
